// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0mXpNEc9usWC1elH6Tlz3st0Jiswnas',
    appId: '1:891183327895:android:e13b97443917e4c4e917d2',
    messagingSenderId: '891183327895',
    projectId: 'supermarket-bd53a',
    storageBucket: 'supermarket-bd53a.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYP9W5Ns9z8hEiR2r4QtMw3igVoKrU1IM',
    appId: '1:891183327895:web:17f8d3a69339d1b6e917d2',
    messagingSenderId: '891183327895',
    projectId: 'supermarket-bd53a',
    authDomain: 'supermarket-bd53a.firebaseapp.com',
    storageBucket: 'supermarket-bd53a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYP9W5Ns9z8hEiR2r4QtMw3igVoKrU1IM',
    appId: '1:891183327895:web:150494637bdac824e917d2',
    messagingSenderId: '891183327895',
    projectId: 'supermarket-bd53a',
    authDomain: 'supermarket-bd53a.firebaseapp.com',
    storageBucket: 'supermarket-bd53a.appspot.com',
  );

}